### ISSUE TITLE
Bitmap into gl10

### ISSUE THREAD

**Issue by dmitrikudrenko** [markfguerra/GLWallpaperService#32]
Sorry for my stupid question, but I am new in opengl. I would like to try your GLWallpaperService, and make myself wallpapers. First of all, I want to add picture like a background, and add some other animation funny things on picture. But I dont know how to add static bitmap on GL10. Can you help me?

**Comment by markfguerra** [comment]
Hi! No questions are stupid, we were all starting out once.

Working with GLWallpaperService is no different from using OpenGL in general on Android (ie, through the GLSurfaceView). Thus, any tutorial for OpenGL in Android applies to wallpapers too. Also, OpenGL has lots of gotchas, you may want to consider reading a book as well to get some concepts down.

The NeHe samples are a great way to get started; they show you how to do all the basic stuff.
http://insanitydesign.com/wp/projects/nehe-android-ports/

For an example of NeHe Lesson 8 (which has a texture\picture) implemented as a wallpaper, look here
https://github.com/markfguerra/GLWallpaperService/tree/master/GLWallpaperTest/src/com/glwallpaperservice/testing/wallpapers/nehe/lesson08

I'm going to close this issue, but only because it's not actually a bug. Good luck with your project!

**Comment by markfguerra** [comment]
By the way, you can find our discussion group here:
https://groups.google.com/forum/#!forum/glwallpaperservice

The group is a better place to ask questions, as more people would see it.

**Comment by dmitrikudrenko** [comment]
Thanks for quick answer and for info-sources!
